### ISSUE TITLE
Unable to read PNG files

### ISSUE THREAD

**Issue by sarthakpati** [bayer-science-for-a-better-life/tiffslide#19]
Hi,

My workflow involves extracting patches from WSI and storing them in PNGs. But when I try to read PNG file, I am getting a tifffile error:

```python-traceback
>>> from tiffslide.tiffslide import TiffSlide
>>> path=r"C:\Projects\GaNDLF\testing\histo_patches\histo_patches_output\1\image\image_patch_3792-13696.png"
>>> TiffSlide(path)
Traceback (most recent call last):
  File "C:\Projects\GaNDLF\venv\lib\site-packages\tifffile\tifffile.py", line 3142, in __init__
    byteorder = {b'II': '<', b'MM': '>', b'EP': '<'}[header[:2]]
KeyError: b'\x89P'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Projects\GaNDLF\venv\lib\site-packages\tiffslide\tiffslide.py", line 107, in __init__
    filename, storage_options=storage_options, tifffile_options=tifffile_options
  File "C:\Projects\GaNDLF\venv\lib\site-packages\tiffslide\tiffslide.py", line 527, in _prepare_tifffile
    return TiffFile(path, **tf_kw)
  File "C:\Projects\GaNDLF\venv\lib\site-packages\tifffile\tifffile.py", line 3144, in __init__
    raise TiffFileError(f'not a TIFF file {header!r}')
tifffile.tifffile.TiffFileError: not a TIFF file b'\x89PNG'
```
![image_patch_3792-13696](https://user-images.githubusercontent.com/11719673/157121877-9182a2df-a9c1-4b4b-9263-51a5229d86e5.png)

Attaching a PNG for reference.

Thanks!

**Comment by sarthakpati** [comment]
Hi Andreas,

Could I recommend (A), since it would be better for downstream integration? Especially when pipelines require wrapper functions like `.level_dimensions`? 😄 

Thanks again!

**Comment by sarthakpati** [comment]
Hey @ap--,

Any update on this?

**Comment by ap--** [comment]
Hey @sarthakpati,

I decided to supported file formats that can be handled by PIL. To reduce future maintenance costs, I think it's best to emulate the TiffFile interface that tiffslide consumes, instead of providing a duplicated implementation of the TiffSlide class. I went through the code and sketched out the interface we'd need to support:

```python
import numpy as np
import zarr

from tiffslide import PathOrFileOrBufferLike


class _PILLevel:
    @property
    def shape(self) -> tuple[int, int]: ...  # fixme: actually longer tuple
    @property
    def size(self) -> int: ...
    @property
    def pages(self) -> list[_PILPage]: ...

class _PILSeries:
    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def levels(self) -> list[_Level]: ...

    def aszarr(self) -> zarr.Array: ...
    def asarray(self) -> np.ndarray: ...


class _PILPage:
    tags = {}
    @property
    def description(self) -> str: ...
    @property
    def tilelength(self) -> int: ...
    @property
    def tilewidth(self) -> int: ...

class _PILFile:

    def __init__(self, f: PathOrFileOrBufferLike, **kwargs): ...  # this should be compatible to TiffFile

    @property
    def series(self) -> list[_PILSeries]: ...  # length 1 list
    @property
    def pages(self) -> list[_PILPage]: ...
    @property
    def filename(self) -> str: ...

    def close(self) -> None: ...
    def __enter__(self) -> _PILFile: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...


class _CompatSlide(TiffSlide):
    def __init__(
        self,
        filename: PathOrFileOrBufferLike[AnyStr],
        *,
        tifffile_options: dict[str, Any] | None = None,
        storage_options: dict[str, Any] | None = None,
    ) -> None:
        self.ts_tifffile = _PILFile(...)  # ensure fsspec compatibility


# Ideally _CompatSlide would only be used as a fallback when opening via `open_slide`

```

Currently I'm very busy with three other projects, so help would be very much appreciated. I'd be of course available for reviewing PRs regarding this and providing feedback. The implementation should be pretty straight forward.

The PR would have to include tests for the new interface. I would parametrize the `svs_small`, `slide` and `svs_small_urlpath` fixtures to use the current testsuite for testing PIL support.


Cheers,
Andreas 😃

**Comment by sarthakpati** [comment]
Thanks for the detailed information! I will circle back with our team to check if anyone has the bandwidth to take this on. 😄

**Comment by sarthakpati** [comment]
Thanks a ton @ap--! 

The conda builds are failing with an error related to zarr but I'll take care of it.
