### ISSUE TITLE
Breaks when running close() after accessing the zarr group

### ISSUE THREAD

**Issue by sdvillal** [bayer-science-for-a-better-life/tiffslide#25]
Minimal example (with one of our prediction images):

```python
with TiffSlide(original_image_path) as original_image:
     _ = original_image.ts_zarr_grp
```

Results in:

```pytb
Traceback (most recent call last):
  File "/Users/santi/Proyectos/--pathology/pathological-suite/palo/palo/recipes/mil/vk_aignostics_test_sets.py", line 95, in <module>
    color_areas(EXAMPLE)
  File "/Users/santi/Proyectos/--pathology/pathological-suite/palo/palo/recipes/mil/vk_aignostics_test_sets.py", line 52, in color_areas
    with TiffSlide(original_image_path) as original_image:
  File "/Users/santi/Proyectos/--pathology/pathological-suite/tiffslide/tiffslide/tiffslide.py", line 98, in __exit__
    self.close()
  File "/Users/santi/Proyectos/--pathology/pathological-suite/tiffslide/tiffslide/tiffslide.py", line 101, in close
    if self._zarr_grp:
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/site-packages/zarr/hierarchy.py", line 238, in __len__
    return sum(1 for _ in self)
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/site-packages/zarr/hierarchy.py", line 238, in <genexpr>
    return sum(1 for _ in self)
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/site-packages/zarr/hierarchy.py", line 232, in __iter__
    if (contains_array(self._store, path) or
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/site-packages/zarr/storage.py", line 96, in contains_array
    return key in store
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/_collections_abc.py", line 822, in __contains__
    self[key]
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/site-packages/zarr/storage.py", line 545, in __getitem__
    return self._mutable_mapping[key]
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/site-packages/tifffile/tifffile.py", line 9086, in __getitem__
    return self._getitem(key)
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/site-packages/tifffile/tifffile.py", line 9562, in _getitem
    keyframe, page, chunkindex, offset, bytecount = self._parse_key(key)
  File "/Users/santi/Utils/mambaforge/envs/pasu/lib/python3.10/site-packages/tifffile/tifffile.py", line 9613, in _parse_key
    series = self._data[int(level)]
ValueError: invalid literal for int() with base 10: '.zattrs'
```

**Comment by sdvillal** [comment]
There might be a regression. I am running 2022.3.16 from conda-forge.

**Comment by cgohlke** [comment]
This is a new error due to another unexpected key/attribute. Tifffile is trying to catch up with the latest changes in zarr...

**Comment by sdvillal** [comment]
Makes sense. Thanks for the prompt answer @cgohlke!

@ap-- Shall we can keep this open until the bug is fixed upstream?

**Comment by cgohlke** [comment]
Should be fixed in [v2022.3.25](https://github.com/cgohlke/tifffile/commit/34282133a09ccaf4b590dc5da41ab8ab2589f5eb)

**Comment by ap--** [comment]
Thanks for the lightning fast fix @cgohlke !

@sdvillal I'll modify the tests to cover this in the CI. I think we'll have to limit the zarr version on python 3.7, or add some compatibility code for the next tiffslide patch version.

**Comment by sdvillal** [comment]
sounds good

could we easily handle this in our close()? what are the resources that leak if we simply ignore the error?

**Comment by ap--** [comment]
That's my guess. I'll check later today and make a new release.

**Comment by sdvillal** [comment]
it can wait

**Comment by ap--** [comment]
Interesting. Only a problem on pypi, because there's `python=3.7` conda packages for `tifffile=2022.3.25`
