### ISSUE TITLE
ValueError when loading region from Aperio .svs

### ISSUE THREAD

**Issue by BenjaminIsaac0111** [bayer-science-for-a-better-life/tiffslide#26]
Hello,

In my workflow, I am trying out Tiffslide as a drop-in replacement for openside.

I am having issues loading a region from a loaded Aperio SVS image. I am passing the same types as I would openslide. Any advice? Possible version incompatibility? 

Some of the WSI I am working with are relatively old (12+ years).

Here is the trace for an example call to .read_region()

```
self.loaded_svs.read_region((9106, 1352), 0, (512, 1028))
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\site-packages\tiffslide\tiffslide.py", line 389, in read_region
    if isinstance(self.ts_zarr_grp, zarr.core.Array):
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\functools.py", line 967, in __get__
    val = self.func(instance)
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\site-packages\tiffslide\tiffslide.py", line 317, in ts_zarr_grp
    return zarr.open(store, mode="r")
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\site-packages\zarr\convenience.py", line 100, in open
    if contains_array(_store, path):
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\site-packages\zarr\storage.py", line 96, in contains_array
    return key in store
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\_collections_abc.py", line 666, in __contains__
    self[key]
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\site-packages\zarr\storage.py", line 545, in __getitem__
    return self._mutable_mapping[key]
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\site-packages\tifffile\tifffile.py", line 8485, in __getitem__
    return self._getitem(key)
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\site-packages\tifffile\tifffile.py", line 8873, in _getitem
    keyframe, page, chunkindex, offset, bytecount = self._parse_key(key)
  File "C:\Users\benja\miniconda3\envs\SVS_Loader\lib\site-packages\tifffile\tifffile.py", line 8914, in _parse_key
    level, key = key.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by ap--** [comment]
Hi @BenjaminIsaac0111,

You just ran into a variant of issue #25 which occurs due to a recent change in the latest version of zarr.
Seeing that you are using conda, you should be able to update `tifffile` to `2022.3.25` and the error should go away.

Cheers,
Andreas 😃

**Comment by BenjaminIsaac0111** [comment]
Amazing, that solved it!

Thanks for the quick response!

Benjamin :D
