### ISSUE TITLE
Cannot parse metadata of tiled-tiff images.

### ISSUE THREAD

**Issue by njlucare** [bayer-science-for-a-better-life/tiffslide#71]
I tried converting a tif image to a tiled tiff image using the tutorial below:

http://www.andrewjanowczyk.com/converting-an-existing-image-into-an-openslide-compatible-format/

However, Tiffslide does not have the ability to parse the metadata, and throws the error ValueError: not enough values to unpack (expected 2, got 1).

This error does not occur if I use the original implementation of openslide, but I get an error when I try to use TiffSlide.

**Comment by ap--** [comment]
Hi @njlucare,

Which version of python and which version of tiffslide are you using?
Also please provide some example code and the exact error message.

Cheers,
Andreas 😊

**Comment by njlucare** [comment]
Python version: 3.7.12
Tiffslide version: 2021.11.2

Entire code sample below:

```
import tiffslide as openslide

im = openslide.OpenSlide('tiled.tif')

print(im.properties)
```

**And here is the traceback:**

```
/home/nlucarelli/HAIL/test.py:14: UserWarning: compatibility: aliasing tiffslide.TiffSlide to 'OpenSlide'
  im = openslide.OpenSlide('/blue/pinaki.sarder/nlucarelli/test_2_tiled.tif')
Traceback (most recent call last):

  File "/scratch/local/62019971/ipykernel_7264/4033020588.py", line 1, in <module>
    runfile('/home/nlucarelli/HAIL/test.py', wdir='/home/nlucarelli/HAIL')

  File "/home/nlucarelli/.conda/envs/det2/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_umd.py", line 175, in runfile
    execfile(filename, namespace)

  File "/home/nlucarelli/.conda/envs/det2/lib/python3.7/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_execfile.py", line 14, in execfile
    exec(compile(contents + "\n", file, 'exec'), glob, loc)

  File "/home/nlucarelli/HAIL/test.py", line 16, in <module>
    print(im.properties)

  File "/home/nlucarelli/.conda/envs/det2/lib/python3.7/site-packages/tiffslide/_pycompat.py", line 135, in __get__
    val = self.func(instance)

  File "/home/nlucarelli/.conda/envs/det2/lib/python3.7/site-packages/tiffslide/tiffslide.py", line 232, in properties
    return _PropertyParser(self._tifffile).parse()

  File "/home/nlucarelli/.conda/envs/det2/lib/python3.7/site-packages/tiffslide/tiffslide.py", line 705, in parse
    return getattr(self, f"parse_{fmt}")()  # type: ignore

  File "/home/nlucarelli/.conda/envs/det2/lib/python3.7/site-packages/tiffslide/tiffslide.py", line 713, in parse_aperio
    md.update(_parse_metadata_aperio(desc))

  File "/home/nlucarelli/.conda/envs/det2/lib/python3.7/site-packages/tiffslide/tiffslide.py", line 794, in _parse_metadata_aperio
    aperio_meta = svs_description_metadata(_aperio_desc)

  File "/home/nlucarelli/.local/lib/python3.7/site-packages/tifffile/tifffile.py", line 15841, in svs_description_metadata
    key, value = item.split(' = ')

ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by ap--** [comment]
Thanks for the info!

You have to upgrade your python version to 3.8 or higher to be able to
install a newer version of tifffile that fixes this bug.

3.7 is only supported for two more months anyways:
https://endoflife.date/python
Time to move on 😊

Cheers
Andreas

**Comment by ap--** [comment]
Let me know if upgrading fixes the issue for you! I'll close this issue for now.

Cheers,
Andreas 😃
